# Generated by Django 3.2.7 on 2022-03-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_auto_20210903_1445'),
        ('sites', '0002_alter_domain_unique'),
        ('news', '0009_whatwearereading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatWeAreReading',
            new_name='WhatWeAreReadingLink',
        ),
    ]
